// ==========================================================
// MÓDULO DOM (v4.3.0)
// Responsabilidade: Centralizar todos os seletores de 
// elementos do DOM da aplicação.
// ==========================================================

// Constantes de UI
export const CHECK_ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" /></svg>`;
export const SIZES_ORDER = [
    'PP', 'P', 'M', 'G', 'GG', 'XG',
    '2 anos', '4 anos', '6 anos', '8 anos', '10 anos', '12 anos'
];

// Centraliza todos os seletores de elementos do DOM
export const DOM = {
    authContainer: document.getElementById('authContainer'),
    loginForm: document.getElementById('loginForm'),
    loginEmail: document.getElementById('loginEmail'),
    loginPassword: document.getElementById('loginPassword'),
    forgotPasswordBtn: document.getElementById('forgotPasswordBtn'),
    logoutBtn: document.getElementById('logoutBtn'),
    userEmail: document.getElementById('userEmail'),
    app: document.getElementById('app'),
    addOrderBtn: document.getElementById('addOrderBtn'),
    backupBtn: document.getElementById('backupBtn'),
    restoreFileInput: document.getElementById('restoreFile'),
    orderModal: document.getElementById('orderModal'),
    orderForm: document.getElementById('orderForm'),
    mainContent: document.getElementById('mainContent'),
    ordersDashboard: document.getElementById('ordersDashboard'),
    financeDashboard: document.getElementById('financeDashboard'),
    ordersList: document.getElementById('ordersList'),
    loadingIndicator: document.getElementById('loadingIndicator'),
    partsContainer: document.getElementById('partsContainer'),
    financialsContainer: document.getElementById('financialsContainer'),
    addPartBtn: document.getElementById('addPartBtn'),
    cancelBtn: document.getElementById('cancelBtn'),
    saveBtn: document.getElementById('saveBtn'),
    uploadIndicator: document.getElementById('uploadIndicator'),
    viewModal: document.getElementById('viewModal'),
    infoModal: document.getElementById('infoModal'),
    infoModalMessage: document.getElementById('infoModalMessage'),
    infoModalCloseBtn: document.getElementById('infoModalCloseBtn'),
    grandTotal: document.getElementById('grandTotal'),
    remainingTotal: document.getElementById('remainingTotal'),
    downPayment: document.getElementById('downPayment'),
    discount: document.getElementById('discount'),
    idleModal: document.getElementById('idleModal'),
    stayLoggedInBtn: document.getElementById('stayLoggedInBtn'),
    countdownTimer: document.getElementById('countdownTimer'),
    optionsModal: document.getElementById('optionsModal'),
    optionsModalTitle: document.getElementById('optionsModalTitle'),
    optionsList: document.getElementById('optionsList'),
    newOptionInput: document.getElementById('newOptionInput'),
    addOptionBtn: document.getElementById('addOptionBtn'),
    closeOptionsModalBtn: document.getElementById('closeOptionsModalBtn'),
    partTypeList: document.getElementById('part-type-list'),
    partMaterialList: document.getElementById('part-material-list'),
    confirmModal: document.getElementById('confirmModal'),
    confirmModalMessage: document.getElementById('confirmModalMessage'),
    confirmOkBtn: document.getElementById('confirmOkBtn'),
    confirmCancelBtn: document.getElementById('confirmCancelBtn'),
    toggleViewBtn: document.getElementById('toggleViewBtn'),
    financeDashboardBtn: document.getElementById('financeDashboardBtn'),
    userMenuBtn: document.getElementById('userMenuBtn'),
    userDropdown: document.getElementById('userDropdown'),
    requestDeletionBtn: document.getElementById('requestDeletionBtn'),
    transactionModal: document.getElementById('transactionModal'),
    transactionForm: document.getElementById('transactionForm'),
    transactionModalTitle: document.getElementById('transactionModalTitle'),
    cancelTransactionBtn: document.getElementById('cancelTransactionBtn'),
    addIncomeBtn: document.getElementById('addIncomeBtn'),
    addExpenseBtn: document.getElementById('addExpenseBtn'),
    transactionsList: document.getElementById('transactionsList'),
    periodFilter: document.getElementById('periodFilter'),
    faturamentoBruto: document.getElementById('faturamentoBruto'),
    despesasTotais: document.getElementById('despesasTotais'),
    contasAReceber: document.getElementById('contasAReceber'),
    lucroLiquido: document.getElementById('lucroLiquido'),
    saldoEmConta: document.getElementById('saldoEmConta'),
    saldoEmCaixa: document.getElementById('saldoEmCaixa'),
    adjustBalanceBtn: document.getElementById('adjustBalanceBtn'),
    initialBalanceModal: document.getElementById('initialBalanceModal'),
    initialBalanceInput: document.getElementById('initialBalanceInput'),
    saveBalanceBtn: document.getElementById('saveBalanceBtn'),
    cancelBalanceBtn: document.getElementById('cancelBalanceBtn'),
    transactionSourceContainer: document.getElementById('transactionSourceContainer'),
    backupReminderBanner: document.getElementById('backupReminderBanner'),
    backupNowBtn: document.getElementById('backupNowBtn'),
    dismissBackupReminderBtn: document.getElementById('dismissBackupReminderBtn'),
    copyReportBtn: document.getElementById('copyReportBtn'),
    customPeriodContainer: document.getElementById('customPeriodContainer'),
    startDateInput: document.getElementById('startDateInput'),
    endDateInput: document.getElementById('endDateInput'),
    transactionCategory: document.getElementById('transactionCategory'),
    topExpensesByCategory: document.getElementById('topExpensesByCategory'),
    topIncomesByCategory: document.getElementById('topIncomesByCategory'),
    transactionSearchInput: document.getElementById('transactionSearchInput'),
    priceTableBtn: document.getElementById('priceTableBtn'),
    priceTableModal: document.getElementById('priceTableModal'),
    priceTableModalTitle: document.getElementById('priceTableModalTitle'),
    priceTableContainer: document.getElementById('priceTableContainer'),
    priceTableFooter: document.getElementById('priceTableFooter'),
    priceTableEditMessage: document.getElementById('priceTableEditMessage'),
    editPriceTableBtn: document.getElementById('editPriceTableBtn'),
    addPriceItemBtn: document.getElementById('addPriceItemBtn'),
    savePriceTableBtn: document.getElementById('savePriceTableBtn'),
    cancelPriceTableBtn: document.getElementById('cancelPriceTableBtn'),
    closePriceTableBtn: document.getElementById('closePriceTableBtn'),
    forgotPasswordModal: document.getElementById('forgotPasswordModal'),
    resetEmailInput: document.getElementById('resetEmailInput'),
    sendResetEmailBtn: document.getElementById('sendResetEmailBtn'),
    cancelResetBtn: document.getElementById('cancelResetBtn'),
    cookieBanner: document.getElementById('cookieBanner'),
    cookieAcceptBtn: document.getElementById('cookieAcceptBtn'),
    transactionDate: document.getElementById('transactionDate'),
    transactionDescription: document.getElementById('transactionDescription'),
    transactionAmount: document.getElementById('transactionAmount'),
    transactionType: document.getElementById('transactionType'),
    transactionId: document.getElementById('transactionId'),
    transactionStatusContainer: document.getElementById('transactionStatusContainer'),
    pago: document.querySelector('input[name="transactionStatus"][value="pago"]'),
    a_receber: document.querySelector('input[name="transactionStatus"][value="a_receber"]'),
    orderId: document.getElementById('orderId'),
    mockupFiles: document.getElementById('mockupFiles'),
    paymentMethod: document.getElementById('paymentMethod'),
    clientName: document.getElementById('clientName'),
    clientPhone: document.getElementById('clientPhone'),
    orderStatus: document.getElementById('orderStatus'),
    orderDate: document.getElementById('orderDate'),
    deliveryDate: document.getElementById('deliveryDate'),
    generalObservation: document.getElementById('generalObservation'),
    existingFilesContainer: document.getElementById('existingFilesContainer'),
    modalTitle: document.getElementById('modalTitle'),
    
    // Novos campos da "Ponte" (v5.0)
    downPaymentDate: document.getElementById('downPaymentDate'),
    downPaymentSourceContainer: document.getElementById('downPaymentSourceContainer'),
    downPaymentStatusContainer: document.getElementById('downPaymentStatusContainer'),
    downPaymentStatusPago: document.querySelector('input[name="downPaymentStatus"][value="pago"]'),
    downPaymentStatusAReceber: document.querySelector('input[name="downPaymentStatus"][value="a_receber"]'),

    // v4.2.7: Modal de Quitação
    settlementModal: document.getElementById('settlementModal'),
    settlementOrderId: document.getElementById('settlementOrderId'),
    settlementAmountDisplay: document.getElementById('settlementAmountDisplay'),
    settlementDate: document.getElementById('settlementDate'),
    settlementSourceContainer: document.getElementById('settlementSourceContainer'),
    settlementCancelBtn: document.getElementById('settlementCancelBtn'),
    settlementConfirmBtn: document.getElementById('settlementConfirmBtn'),
};
